const studentResultData = {
  profile: {
    grade: "A",
    noInClass: 16,
    portalId: 4317,
    classAvg: 71.84,
    gender: "FEMALE",
    year: "2022/2023",
    term: "FIRST TERM",
    markObtained: 1463,
    avgPercentage: 91.44,
    class: "JS3 DIAMOND",
    name: "Divine Domokuma",
    maxMarkObtainable: 1600,
  },
  resultData: [
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "AGRICULTURE",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "C",
      subject: "CREATIVE AND CULTURAL ARTS",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "5th",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "BUSINESS STUDIES",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "2nd",
    },
    {
      test: 20,
      exam: 45,
      total: 79,
      grade: "A",
      subject: "BASIC SCIENCE",
      assignment: 15,
      classAvg: 58.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 30,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "COMPUTER SCIENCE",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 13,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "CRS",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "BASIC TECHNOLOGY",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "SECURITY EDUCATION",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "ENGLISH LANGUAGE",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "CIVIC EDUCATION",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "FRENCH",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "HOME ECONOMICS",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "C",
      subject: "IGBO LANGUAGE",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "PHE",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "MATHEMATICS",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
    {
      test: 20,
      exam: 55,
      total: 79,
      grade: "A",
      subject: "SOCIAL STUDIES",
      assignment: 15,
      classAvg: 78.4,
      verdict: "PASS",
      remarks: "EXCELLENT",
      subjectPosition: "3rd",
    },
  ],
  remarks: {
    principal: "She is focused during lessons and contributes willingly",
    teacher: "  AN EXCELLENT RESULT",
  },
};

export default studentResultData;
